// flow-typed signature: dc5873a22e2d6aeb2dea5a8cd7fa7b6b
// flow-typed version: <<STUB>>/eslint-config-last_v0.0.5/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-last'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-last' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-last/index' {
  declare module.exports: $Exports<'eslint-config-last'>;
}
declare module 'eslint-config-last/index.js' {
  declare module.exports: $Exports<'eslint-config-last'>;
}
