// flow-typed signature: 538d97646afb3bc43c09e1805a9647f8
// flow-typed version: <<STUB>>/flickity_v^2.1.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flickity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flickity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flickity/dist/flickity.pkgd' {
  declare module.exports: any;
}

declare module 'flickity/dist/flickity.pkgd.min' {
  declare module.exports: any;
}

declare module 'flickity/gulpfile' {
  declare module.exports: any;
}

declare module 'flickity/js/add-remove-cell' {
  declare module.exports: any;
}

declare module 'flickity/js/animate' {
  declare module.exports: any;
}

declare module 'flickity/js/cell' {
  declare module.exports: any;
}

declare module 'flickity/js/drag' {
  declare module.exports: any;
}

declare module 'flickity/js/flickity' {
  declare module.exports: any;
}

declare module 'flickity/js/index' {
  declare module.exports: any;
}

declare module 'flickity/js/lazyload' {
  declare module.exports: any;
}

declare module 'flickity/js/page-dots' {
  declare module.exports: any;
}

declare module 'flickity/js/player' {
  declare module.exports: any;
}

declare module 'flickity/js/prev-next-button' {
  declare module.exports: any;
}

declare module 'flickity/js/slide' {
  declare module.exports: any;
}

declare module 'flickity/sandbox/browserify/main' {
  declare module.exports: any;
}

declare module 'flickity/sandbox/requirejs/main' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/adaptive-height' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/add-remove-cells' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/auto-play' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/cell-selector' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/change' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/contain' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/destroy' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/drag' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/empty' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/get-parent-cell' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/get-wrap-cells' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/group-cells' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/init' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/lazyload-srcset' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/lazyload' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/page-dots' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/position-cells' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/prev-next-buttons' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/resize' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/select-cell' {
  declare module.exports: any;
}

declare module 'flickity/test/unit/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flickity/dist/flickity.pkgd.js' {
  declare module.exports: $Exports<'flickity/dist/flickity.pkgd'>;
}
declare module 'flickity/dist/flickity.pkgd.min.js' {
  declare module.exports: $Exports<'flickity/dist/flickity.pkgd.min'>;
}
declare module 'flickity/gulpfile.js' {
  declare module.exports: $Exports<'flickity/gulpfile'>;
}
declare module 'flickity/js/add-remove-cell.js' {
  declare module.exports: $Exports<'flickity/js/add-remove-cell'>;
}
declare module 'flickity/js/animate.js' {
  declare module.exports: $Exports<'flickity/js/animate'>;
}
declare module 'flickity/js/cell.js' {
  declare module.exports: $Exports<'flickity/js/cell'>;
}
declare module 'flickity/js/drag.js' {
  declare module.exports: $Exports<'flickity/js/drag'>;
}
declare module 'flickity/js/flickity.js' {
  declare module.exports: $Exports<'flickity/js/flickity'>;
}
declare module 'flickity/js/index.js' {
  declare module.exports: $Exports<'flickity/js/index'>;
}
declare module 'flickity/js/lazyload.js' {
  declare module.exports: $Exports<'flickity/js/lazyload'>;
}
declare module 'flickity/js/page-dots.js' {
  declare module.exports: $Exports<'flickity/js/page-dots'>;
}
declare module 'flickity/js/player.js' {
  declare module.exports: $Exports<'flickity/js/player'>;
}
declare module 'flickity/js/prev-next-button.js' {
  declare module.exports: $Exports<'flickity/js/prev-next-button'>;
}
declare module 'flickity/js/slide.js' {
  declare module.exports: $Exports<'flickity/js/slide'>;
}
declare module 'flickity/sandbox/browserify/main.js' {
  declare module.exports: $Exports<'flickity/sandbox/browserify/main'>;
}
declare module 'flickity/sandbox/requirejs/main.js' {
  declare module.exports: $Exports<'flickity/sandbox/requirejs/main'>;
}
declare module 'flickity/test/unit/adaptive-height.js' {
  declare module.exports: $Exports<'flickity/test/unit/adaptive-height'>;
}
declare module 'flickity/test/unit/add-remove-cells.js' {
  declare module.exports: $Exports<'flickity/test/unit/add-remove-cells'>;
}
declare module 'flickity/test/unit/auto-play.js' {
  declare module.exports: $Exports<'flickity/test/unit/auto-play'>;
}
declare module 'flickity/test/unit/cell-selector.js' {
  declare module.exports: $Exports<'flickity/test/unit/cell-selector'>;
}
declare module 'flickity/test/unit/change.js' {
  declare module.exports: $Exports<'flickity/test/unit/change'>;
}
declare module 'flickity/test/unit/contain.js' {
  declare module.exports: $Exports<'flickity/test/unit/contain'>;
}
declare module 'flickity/test/unit/destroy.js' {
  declare module.exports: $Exports<'flickity/test/unit/destroy'>;
}
declare module 'flickity/test/unit/drag.js' {
  declare module.exports: $Exports<'flickity/test/unit/drag'>;
}
declare module 'flickity/test/unit/empty.js' {
  declare module.exports: $Exports<'flickity/test/unit/empty'>;
}
declare module 'flickity/test/unit/get-parent-cell.js' {
  declare module.exports: $Exports<'flickity/test/unit/get-parent-cell'>;
}
declare module 'flickity/test/unit/get-wrap-cells.js' {
  declare module.exports: $Exports<'flickity/test/unit/get-wrap-cells'>;
}
declare module 'flickity/test/unit/group-cells.js' {
  declare module.exports: $Exports<'flickity/test/unit/group-cells'>;
}
declare module 'flickity/test/unit/init.js' {
  declare module.exports: $Exports<'flickity/test/unit/init'>;
}
declare module 'flickity/test/unit/lazyload-srcset.js' {
  declare module.exports: $Exports<'flickity/test/unit/lazyload-srcset'>;
}
declare module 'flickity/test/unit/lazyload.js' {
  declare module.exports: $Exports<'flickity/test/unit/lazyload'>;
}
declare module 'flickity/test/unit/page-dots.js' {
  declare module.exports: $Exports<'flickity/test/unit/page-dots'>;
}
declare module 'flickity/test/unit/position-cells.js' {
  declare module.exports: $Exports<'flickity/test/unit/position-cells'>;
}
declare module 'flickity/test/unit/prev-next-buttons.js' {
  declare module.exports: $Exports<'flickity/test/unit/prev-next-buttons'>;
}
declare module 'flickity/test/unit/resize.js' {
  declare module.exports: $Exports<'flickity/test/unit/resize'>;
}
declare module 'flickity/test/unit/select-cell.js' {
  declare module.exports: $Exports<'flickity/test/unit/select-cell'>;
}
declare module 'flickity/test/unit/watch.js' {
  declare module.exports: $Exports<'flickity/test/unit/watch'>;
}
