// flow-typed signature: a73b3dea78d38477378f7b22dfa0e610
// flow-typed version: <<STUB>>/github-markdown-css_v^2.10.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-markdown-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-markdown-css' {
  declare module.exports: any;
}
