// flow-typed signature: 6923187acb779d439015594a4202080a
// flow-typed version: <<STUB>>/hackmyresume_v^1.9.0-beta/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hackmyresume'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hackmyresume' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hackmyresume/dist/cli/error' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/cli/index' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/cli/main' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/cli/msg' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/cli/out' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/default-formats' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/default-options' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/event-codes' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/fluent-date' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/fresh-resume' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/fresh-theme' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/jrs-resume' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/jrs-theme' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/resume-factory' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/core/status-codes' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/base-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/html-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/html-pdf-cli-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/html-png-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/json-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/json-yaml-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/latex-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/markdown-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/template-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/text-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/word-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/xml-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/generators/yaml-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/helpers/block-helpers' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/helpers/console-helpers' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/helpers/generic-helpers' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/helpers/handlebars-helpers' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/helpers/underscore-helpers' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/index' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/inspectors/duration-inspector' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/inspectors/gap-inspector' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/inspectors/keyword-inspector' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/inspectors/totals-inspector' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/renderers/handlebars-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/renderers/jrs-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/renderers/underscore-generator' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/file-contains' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/fresh-version-regex' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/html-to-wpml' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/md2chalk' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/rasterize' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/resume-detector' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/resume-scrubber' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/safe-json-loader' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/safe-spawn' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/string-transformer' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/string' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/utils/syntax-error-ex' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/verbs/analyze' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/verbs/build' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/verbs/convert' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/verbs/create' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/verbs/peek' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/verbs/validate' {
  declare module.exports: any;
}

declare module 'hackmyresume/dist/verbs/verb' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hackmyresume/dist/cli/error.js' {
  declare module.exports: $Exports<'hackmyresume/dist/cli/error'>;
}
declare module 'hackmyresume/dist/cli/index.js' {
  declare module.exports: $Exports<'hackmyresume/dist/cli/index'>;
}
declare module 'hackmyresume/dist/cli/main.js' {
  declare module.exports: $Exports<'hackmyresume/dist/cli/main'>;
}
declare module 'hackmyresume/dist/cli/msg.js' {
  declare module.exports: $Exports<'hackmyresume/dist/cli/msg'>;
}
declare module 'hackmyresume/dist/cli/out.js' {
  declare module.exports: $Exports<'hackmyresume/dist/cli/out'>;
}
declare module 'hackmyresume/dist/core/default-formats.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/default-formats'>;
}
declare module 'hackmyresume/dist/core/default-options.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/default-options'>;
}
declare module 'hackmyresume/dist/core/event-codes.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/event-codes'>;
}
declare module 'hackmyresume/dist/core/fluent-date.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/fluent-date'>;
}
declare module 'hackmyresume/dist/core/fresh-resume.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/fresh-resume'>;
}
declare module 'hackmyresume/dist/core/fresh-theme.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/fresh-theme'>;
}
declare module 'hackmyresume/dist/core/jrs-resume.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/jrs-resume'>;
}
declare module 'hackmyresume/dist/core/jrs-theme.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/jrs-theme'>;
}
declare module 'hackmyresume/dist/core/resume-factory.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/resume-factory'>;
}
declare module 'hackmyresume/dist/core/status-codes.js' {
  declare module.exports: $Exports<'hackmyresume/dist/core/status-codes'>;
}
declare module 'hackmyresume/dist/generators/base-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/base-generator',
  >;
}
declare module 'hackmyresume/dist/generators/html-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/html-generator',
  >;
}
declare module 'hackmyresume/dist/generators/html-pdf-cli-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/html-pdf-cli-generator',
  >;
}
declare module 'hackmyresume/dist/generators/html-png-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/html-png-generator',
  >;
}
declare module 'hackmyresume/dist/generators/json-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/json-generator',
  >;
}
declare module 'hackmyresume/dist/generators/json-yaml-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/json-yaml-generator',
  >;
}
declare module 'hackmyresume/dist/generators/latex-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/latex-generator',
  >;
}
declare module 'hackmyresume/dist/generators/markdown-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/markdown-generator',
  >;
}
declare module 'hackmyresume/dist/generators/template-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/template-generator',
  >;
}
declare module 'hackmyresume/dist/generators/text-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/text-generator',
  >;
}
declare module 'hackmyresume/dist/generators/word-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/word-generator',
  >;
}
declare module 'hackmyresume/dist/generators/xml-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/xml-generator',
  >;
}
declare module 'hackmyresume/dist/generators/yaml-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/generators/yaml-generator',
  >;
}
declare module 'hackmyresume/dist/helpers/block-helpers.js' {
  declare module.exports: $Exports<'hackmyresume/dist/helpers/block-helpers'>;
}
declare module 'hackmyresume/dist/helpers/console-helpers.js' {
  declare module.exports: $Exports<'hackmyresume/dist/helpers/console-helpers'>;
}
declare module 'hackmyresume/dist/helpers/generic-helpers.js' {
  declare module.exports: $Exports<'hackmyresume/dist/helpers/generic-helpers'>;
}
declare module 'hackmyresume/dist/helpers/handlebars-helpers.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/helpers/handlebars-helpers',
  >;
}
declare module 'hackmyresume/dist/helpers/underscore-helpers.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/helpers/underscore-helpers',
  >;
}
declare module 'hackmyresume/dist/index.js' {
  declare module.exports: $Exports<'hackmyresume/dist/index'>;
}
declare module 'hackmyresume/dist/inspectors/duration-inspector.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/inspectors/duration-inspector',
  >;
}
declare module 'hackmyresume/dist/inspectors/gap-inspector.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/inspectors/gap-inspector',
  >;
}
declare module 'hackmyresume/dist/inspectors/keyword-inspector.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/inspectors/keyword-inspector',
  >;
}
declare module 'hackmyresume/dist/inspectors/totals-inspector.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/inspectors/totals-inspector',
  >;
}
declare module 'hackmyresume/dist/renderers/handlebars-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/renderers/handlebars-generator',
  >;
}
declare module 'hackmyresume/dist/renderers/jrs-generator.js' {
  declare module.exports: $Exports<'hackmyresume/dist/renderers/jrs-generator'>;
}
declare module 'hackmyresume/dist/renderers/underscore-generator.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/renderers/underscore-generator',
  >;
}
declare module 'hackmyresume/dist/utils/file-contains.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/file-contains'>;
}
declare module 'hackmyresume/dist/utils/fresh-version-regex.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/utils/fresh-version-regex',
  >;
}
declare module 'hackmyresume/dist/utils/html-to-wpml.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/html-to-wpml'>;
}
declare module 'hackmyresume/dist/utils/md2chalk.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/md2chalk'>;
}
declare module 'hackmyresume/dist/utils/rasterize.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/rasterize'>;
}
declare module 'hackmyresume/dist/utils/resume-detector.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/resume-detector'>;
}
declare module 'hackmyresume/dist/utils/resume-scrubber.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/resume-scrubber'>;
}
declare module 'hackmyresume/dist/utils/safe-json-loader.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/safe-json-loader'>;
}
declare module 'hackmyresume/dist/utils/safe-spawn.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/safe-spawn'>;
}
declare module 'hackmyresume/dist/utils/string-transformer.js' {
  declare module.exports: $Exports<
    'hackmyresume/dist/utils/string-transformer',
  >;
}
declare module 'hackmyresume/dist/utils/string.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/string'>;
}
declare module 'hackmyresume/dist/utils/syntax-error-ex.js' {
  declare module.exports: $Exports<'hackmyresume/dist/utils/syntax-error-ex'>;
}
declare module 'hackmyresume/dist/verbs/analyze.js' {
  declare module.exports: $Exports<'hackmyresume/dist/verbs/analyze'>;
}
declare module 'hackmyresume/dist/verbs/build.js' {
  declare module.exports: $Exports<'hackmyresume/dist/verbs/build'>;
}
declare module 'hackmyresume/dist/verbs/convert.js' {
  declare module.exports: $Exports<'hackmyresume/dist/verbs/convert'>;
}
declare module 'hackmyresume/dist/verbs/create.js' {
  declare module.exports: $Exports<'hackmyresume/dist/verbs/create'>;
}
declare module 'hackmyresume/dist/verbs/peek.js' {
  declare module.exports: $Exports<'hackmyresume/dist/verbs/peek'>;
}
declare module 'hackmyresume/dist/verbs/validate.js' {
  declare module.exports: $Exports<'hackmyresume/dist/verbs/validate'>;
}
declare module 'hackmyresume/dist/verbs/verb.js' {
  declare module.exports: $Exports<'hackmyresume/dist/verbs/verb'>;
}
