// flow-typed signature: 038767fc8d3c8a5c8340476fc9e8724b
// flow-typed version: <<STUB>>/handlebars-helpers_v^0.10.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'handlebars-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'handlebars-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'handlebars-helpers/lib/array' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/code' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/collection' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/comparison' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/date' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/fs' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/html' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/i18n' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/index' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/inflection' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/logging' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/markdown' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/match' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/math' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/misc' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/number' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/object' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/path' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/regex' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/string' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/url' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/utils/html' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/utils/index' {
  declare module.exports: any;
}

declare module 'handlebars-helpers/lib/utils/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'handlebars-helpers/index' {
  declare module.exports: $Exports<'handlebars-helpers'>;
}
declare module 'handlebars-helpers/index.js' {
  declare module.exports: $Exports<'handlebars-helpers'>;
}
declare module 'handlebars-helpers/lib/array.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/array'>;
}
declare module 'handlebars-helpers/lib/code.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/code'>;
}
declare module 'handlebars-helpers/lib/collection.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/collection'>;
}
declare module 'handlebars-helpers/lib/comparison.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/comparison'>;
}
declare module 'handlebars-helpers/lib/date.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/date'>;
}
declare module 'handlebars-helpers/lib/fs.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/fs'>;
}
declare module 'handlebars-helpers/lib/html.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/html'>;
}
declare module 'handlebars-helpers/lib/i18n.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/i18n'>;
}
declare module 'handlebars-helpers/lib/index.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/index'>;
}
declare module 'handlebars-helpers/lib/inflection.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/inflection'>;
}
declare module 'handlebars-helpers/lib/logging.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/logging'>;
}
declare module 'handlebars-helpers/lib/markdown.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/markdown'>;
}
declare module 'handlebars-helpers/lib/match.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/match'>;
}
declare module 'handlebars-helpers/lib/math.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/math'>;
}
declare module 'handlebars-helpers/lib/misc.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/misc'>;
}
declare module 'handlebars-helpers/lib/number.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/number'>;
}
declare module 'handlebars-helpers/lib/object.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/object'>;
}
declare module 'handlebars-helpers/lib/path.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/path'>;
}
declare module 'handlebars-helpers/lib/regex.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/regex'>;
}
declare module 'handlebars-helpers/lib/string.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/string'>;
}
declare module 'handlebars-helpers/lib/url.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/url'>;
}
declare module 'handlebars-helpers/lib/utils/html.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/utils/html'>;
}
declare module 'handlebars-helpers/lib/utils/index.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/utils/index'>;
}
declare module 'handlebars-helpers/lib/utils/utils.js' {
  declare module.exports: $Exports<'handlebars-helpers/lib/utils/utils'>;
}
