// flow-typed signature: d733d3ac7a286ddc68b5d70e36fe7f9b
// flow-typed version: <<STUB>>/markdown-with-front-matter-loader_v^0.1.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-with-front-matter-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-with-front-matter-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'markdown-with-front-matter-loader/index' {
  declare module.exports: $Exports<'markdown-with-front-matter-loader'>;
}
declare module 'markdown-with-front-matter-loader/index.js' {
  declare module.exports: $Exports<'markdown-with-front-matter-loader'>;
}
