// flow-typed signature: f580f3bc8166d369275843f937818134
// flow-typed version: <<STUB>>/markdown-image-loader_v^1.0.5/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-image-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-image-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'markdown-image-loader/index' {
  declare module.exports: $Exports<'markdown-image-loader'>;
}
declare module 'markdown-image-loader/index.js' {
  declare module.exports: $Exports<'markdown-image-loader'>;
}
