// flow-typed signature: 5d838a24069aedc6196db1e0993edd10
// flow-typed version: <<STUB>>/markdown-with-front-matter-loader_v^0.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-with-front-matter-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-with-front-matter-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'markdown-with-front-matter-loader/index' {
  declare module.exports: $Exports<'markdown-with-front-matter-loader'>;
}
declare module 'markdown-with-front-matter-loader/index.js' {
  declare module.exports: $Exports<'markdown-with-front-matter-loader'>;
}
