// flow-typed signature: 806d5a784f4d7b2a3d96322a01b982f8
// flow-typed version: <<STUB>>/masonry-layout_v^4.2.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'masonry-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'masonry-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'masonry-layout/dist/masonry.pkgd' {
  declare module.exports: any;
}

declare module 'masonry-layout/dist/masonry.pkgd.min' {
  declare module.exports: any;
}

declare module 'masonry-layout/masonry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'masonry-layout/dist/masonry.pkgd.js' {
  declare module.exports: $Exports<'masonry-layout/dist/masonry.pkgd'>;
}
declare module 'masonry-layout/dist/masonry.pkgd.min.js' {
  declare module.exports: $Exports<'masonry-layout/dist/masonry.pkgd.min'>;
}
declare module 'masonry-layout/masonry.js' {
  declare module.exports: $Exports<'masonry-layout/masonry'>;
}
