// flow-typed signature: 6491396421642be879ed27e9bdb59364
// flow-typed version: <<STUB>>/pace-js_v^1.0.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pace-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pace-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pace-js/docs/lib/color' {
  declare module.exports: any;
}

declare module 'pace-js/docs/lib/themes' {
  declare module.exports: any;
}

declare module 'pace-js/pace' {
  declare module.exports: any;
}

declare module 'pace-js/pace.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pace-js/docs/lib/color.js' {
  declare module.exports: $Exports<'pace-js/docs/lib/color'>;
}
declare module 'pace-js/docs/lib/themes.js' {
  declare module.exports: $Exports<'pace-js/docs/lib/themes'>;
}
declare module 'pace-js/pace.js' {
  declare module.exports: $Exports<'pace-js/pace'>;
}
declare module 'pace-js/pace.min.js' {
  declare module.exports: $Exports<'pace-js/pace.min'>;
}
