// flow-typed signature: 8be5b678dda20b1a82c1d3cf3bc4f623
// flow-typed version: <<STUB>>/react-slide-toggle_v^0.1.13/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slide-toggle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slide-toggle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slide-toggle/dist/ReactSlideToggle.umd' {
  declare module.exports: any;
}

declare module 'react-slide-toggle/dist/ReactSlideToggle.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slide-toggle/dist/ReactSlideToggle.umd.js' {
  declare module.exports: $Exports<'react-slide-toggle/dist/ReactSlideToggle.umd'>;
}
declare module 'react-slide-toggle/dist/ReactSlideToggle.umd.min.js' {
  declare module.exports: $Exports<'react-slide-toggle/dist/ReactSlideToggle.umd.min'>;
}
