// flow-typed signature: 46a3c76ecdf4e51ee13e89306cf0eb8e
// flow-typed version: <<STUB>>/react-snapshot-sitemap_v^0.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-snapshot-sitemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-snapshot-sitemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-snapshot-sitemap/bin/react-snapshot-sitemap' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/lib/cli' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/lib/Crawler' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/lib/index' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/lib/Server' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/lib/snapshot' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/lib/Writer' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/src/cli' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/src/Crawler' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/src/index' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/src/Server' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/src/snapshot' {
  declare module.exports: any;
}

declare module 'react-snapshot-sitemap/src/Writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-snapshot-sitemap/bin/react-snapshot-sitemap.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/bin/react-snapshot-sitemap'>;
}
declare module 'react-snapshot-sitemap/lib/cli.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/lib/cli'>;
}
declare module 'react-snapshot-sitemap/lib/Crawler.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/lib/Crawler'>;
}
declare module 'react-snapshot-sitemap/lib/index.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/lib/index'>;
}
declare module 'react-snapshot-sitemap/lib/Server.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/lib/Server'>;
}
declare module 'react-snapshot-sitemap/lib/snapshot.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/lib/snapshot'>;
}
declare module 'react-snapshot-sitemap/lib/Writer.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/lib/Writer'>;
}
declare module 'react-snapshot-sitemap/src/cli.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/src/cli'>;
}
declare module 'react-snapshot-sitemap/src/Crawler.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/src/Crawler'>;
}
declare module 'react-snapshot-sitemap/src/index.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/src/index'>;
}
declare module 'react-snapshot-sitemap/src/Server.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/src/Server'>;
}
declare module 'react-snapshot-sitemap/src/snapshot.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/src/snapshot'>;
}
declare module 'react-snapshot-sitemap/src/Writer.js' {
  declare module.exports: $Exports<'react-snapshot-sitemap/src/Writer'>;
}
