// flow-typed signature: 9343829dba7a2f20e31145bc0b3fc73c
// flow-typed version: <<STUB>>/react-flickity-component_v^3.0.3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-flickity-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-flickity-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-flickity-component/__tests__/component.spec' {
  declare module.exports: any;
}

declare module 'react-flickity-component/lib/index' {
  declare module.exports: any;
}

declare module 'react-flickity-component/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-flickity-component/__tests__/component.spec.js' {
  declare module.exports: $Exports<
    'react-flickity-component/__tests__/component.spec',
  >;
}
declare module 'react-flickity-component/lib/index.js' {
  declare module.exports: $Exports<'react-flickity-component/lib/index'>;
}
declare module 'react-flickity-component/src/index.js' {
  declare module.exports: $Exports<'react-flickity-component/src/index'>;
}
