// flow-typed signature: ad3b8cb5fc9d81cf160c536f3cd837cd
// flow-typed version: <<STUB>>/react-waypoint_v^8.0.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-waypoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-waypoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-waypoint/build/index' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/performance-test' {
  declare module.exports: any;
}

declare module 'react-waypoint/cjs/index' {
  declare module.exports: any;
}

declare module 'react-waypoint/es/index' {
  declare module.exports: any;
}

declare module 'react-waypoint/rollup.config' {
  declare module.exports: any;
}

declare module 'react-waypoint/webpack.config.performance-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-waypoint/build/index.js' {
  declare module.exports: $Exports<'react-waypoint/build/index'>;
}
declare module 'react-waypoint/build/performance-test.js' {
  declare module.exports: $Exports<'react-waypoint/build/performance-test'>;
}
declare module 'react-waypoint/cjs/index.js' {
  declare module.exports: $Exports<'react-waypoint/cjs/index'>;
}
declare module 'react-waypoint/es/index.js' {
  declare module.exports: $Exports<'react-waypoint/es/index'>;
}
declare module 'react-waypoint/rollup.config.js' {
  declare module.exports: $Exports<'react-waypoint/rollup.config'>;
}
declare module 'react-waypoint/webpack.config.performance-test.js' {
  declare module.exports: $Exports<'react-waypoint/webpack.config.performance-test'>;
}
