// flow-typed signature: 8d8e97e8ee9604cc9af72a1b492faa2e
// flow-typed version: <<STUB>>/react-photoswipe_v^1.3.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-photoswipe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-photoswipe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-photoswipe/dist/react-photoswipe' {
  declare module.exports: any;
}

declare module 'react-photoswipe/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-photoswipe/lib/events' {
  declare module.exports: any;
}

declare module 'react-photoswipe/lib/index' {
  declare module.exports: any;
}

declare module 'react-photoswipe/lib/PhotoSwipe' {
  declare module.exports: any;
}

declare module 'react-photoswipe/lib/PhotoSwipeGallery' {
  declare module.exports: any;
}

declare module 'react-photoswipe/postcss.config' {
  declare module.exports: any;
}

declare module 'react-photoswipe/src/events' {
  declare module.exports: any;
}

declare module 'react-photoswipe/src/index' {
  declare module.exports: any;
}

declare module 'react-photoswipe/src/PhotoSwipe' {
  declare module.exports: any;
}

declare module 'react-photoswipe/src/PhotoSwipeGallery' {
  declare module.exports: any;
}

declare module 'react-photoswipe/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-photoswipe/dist/react-photoswipe.js' {
  declare module.exports: $Exports<'react-photoswipe/dist/react-photoswipe'>;
}
declare module 'react-photoswipe/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-photoswipe/gulpfile.babel'>;
}
declare module 'react-photoswipe/lib/events.js' {
  declare module.exports: $Exports<'react-photoswipe/lib/events'>;
}
declare module 'react-photoswipe/lib/index.js' {
  declare module.exports: $Exports<'react-photoswipe/lib/index'>;
}
declare module 'react-photoswipe/lib/PhotoSwipe.js' {
  declare module.exports: $Exports<'react-photoswipe/lib/PhotoSwipe'>;
}
declare module 'react-photoswipe/lib/PhotoSwipeGallery.js' {
  declare module.exports: $Exports<'react-photoswipe/lib/PhotoSwipeGallery'>;
}
declare module 'react-photoswipe/postcss.config.js' {
  declare module.exports: $Exports<'react-photoswipe/postcss.config'>;
}
declare module 'react-photoswipe/src/events.js' {
  declare module.exports: $Exports<'react-photoswipe/src/events'>;
}
declare module 'react-photoswipe/src/index.js' {
  declare module.exports: $Exports<'react-photoswipe/src/index'>;
}
declare module 'react-photoswipe/src/PhotoSwipe.js' {
  declare module.exports: $Exports<'react-photoswipe/src/PhotoSwipe'>;
}
declare module 'react-photoswipe/src/PhotoSwipeGallery.js' {
  declare module.exports: $Exports<'react-photoswipe/src/PhotoSwipeGallery'>;
}
declare module 'react-photoswipe/webpack.config.js' {
  declare module.exports: $Exports<'react-photoswipe/webpack.config'>;
}
