// flow-typed signature: 10845996941ab4818b2e0478ad94e1bd
// flow-typed version: <<STUB>>/rellax_v^1.6.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rellax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rellax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rellax/rellax' {
  declare module.exports: any;
}

declare module 'rellax/rellax.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rellax/rellax.js' {
  declare module.exports: $Exports<'rellax/rellax'>;
}
declare module 'rellax/rellax.min.js' {
  declare module.exports: $Exports<'rellax/rellax.min'>;
}
